version: 1
accounts:
- name: validator1
  coins:
  - 8000000000000000000000000000uxoc
client:
  openapi:
    path: docs/static/openapi.yml
validators:
- name: validator1
  bonded: 2000000000000000000000uxoc
  home: "$HOME/.xone"
  app:
     minimum-gas-prices: "10000000uxoc"
     api:
         enable: true
         enabled-unsafe-cors: true
         address: "tcp://0.0.0.0:1317"
     grpc:
         enable: true
         address: "0.0.0.0:9090"
     grpc-web:
         address: "0.0.0.0:9091"
         enable: true
         enable-unsafe-cors: true
  config:
     consensus:
         timeout_commit: "3s"
     proxy_app: "tcp://0.0.0.0:26658"
     moniker: "node1"
     rpc:
         max_body_bytes: "10240000"
         laddr: "tcp://0.0.0.0:26657"
     p2p:
         laddr: "tcp://0.0.0.0:26656"
         persistent_peers: ""
         allow_duplicate_ip: true
     instrumentation:
         prometheus: true
         prometheus_listen_addr: ":26660"
genesis:
  chain_id: "xone_33772211-1"
  initial_height: "1"
  genesis_time: "2023-11-09T07:46:56.293077949Z"
  consensus_params:
    block:
      max_gas: "1000000000"
    version:
      app: "9160"
  app_state:
    evm:
      params:
        evm_denom: "uxoc"
    claims:
      params:
        claims_denom: "uxoc"
    feemarket:
      params:
        base_fee: "5000000"
        min_gas_price: "10000000"
        base_fee_change_denominator: 8
        elasticity_multiplier: 2
        enable_height: 0
        min_gas_multiplier: "0.500000000000000000"
        no_base_fee: false
    bank:
      denom_metadata:
        - description: "The native token"
          base: "uxoc"
          display: "xoc"
          name: "mint token"
          symbol: "XOC"
          denom_units:
            - aliases: [ ]
              denom: "uxoc"
              exponent: 0
            - aliases: [ ]
              denom: "axoc"
              exponent: 9
            - aliases: [ ]
              denom: "xoc"
              exponent: 18
    crisis:
      constant_fee:
        amount: "10000000000000000000"
        denom: "uxoc"
    mint:
      minter:
        annual_provisions: "0.000000000000000000"
        inflation: "0.000000000000000000"
      params:
        mint_denom: "uxoc"
        blocks_per_year: "4505142"
        goal_bonded: "0.670000000000000000"
        inflation_max: "0.200000000000000000"
        inflation_min: "0.070000000000000000"
        inflation_rate_change: "0.130000000000000000"
    gov:
      params:
        min_deposit:
          - amount: "100000000000000000000"
            denom: "uxoc"
    staking:
      params:
        bond_denom: "uxoc"
        min_commission_rate: "0.05"
        unbonding_time: "60s"